### ISSUE TITLE
How can we test notebooks?

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/jupyter-interactions#1]
Libraries change over time...how can we flag up notebooks that don't work on latest versions of things?

**Comment by willfurnass** [comment]
And how can we test the use of widgets?  Could we use the [hypothesis] testing tool (https://hypothesis.readthedocs.io/en/latest/) to validate that the examples work over the input space?

**Comment by mikecroucher** [comment]
I'm going to take a look at this using nbval

**Comment by mikecroucher** [comment]
Done using Travis and nbval
