### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by christianp** [mikecroucher/jupyter-interactions#26]
What licence should *(a)* this repository, and *(b)* the submitted notebooks be released under?

CC-BY would be appropriate for the notebooks. The linter should check for a copyright and licence declaration.

I'm happy to put the code to make the website under MIT or Apache.

**Comment by mikecroucher** [comment]
Sounds good to me.

**Comment by christianp** [comment]
OK. I suppose we need to get the authors of each of the existing interactions to submit new versions with copyright statements, or comment here saying that CC-BY is OK.

**Comment by mikecroucher** [comment]
Well I'm OK with it. The only other people who need to agree are @pedritomelenas @rgaiacs and @trallard I think

**Comment by rgaiacs** [comment]
I'm OK. Just let me know what the procedure that you want me to follow.

**Comment by pedritomelenas** [comment]
It is fine with me.
Thanks for pointing this.

**Comment by trallard** [comment]
I am cool with this

**Comment by mikecroucher** [comment]
License notice added to template.  https://github.com/mikecroucher/jupyter-interactions/blob/master/template.ipynb 

If anyone would like to resubmit their notebook with this added, that would be great.

**Comment by christianp** [comment]
Since everyone gave the OK, I've edited the existing templates.

**Comment by mikecroucher** [comment]
thanks
