### ISSUE TITLE
Use list instead of comma separated value?

### ISSUE THREAD

**Issue by rgaiacs** [mikecroucher/jupyter-interactions#28]
We use lists for references and we could use lists instead of comma separated value for keywords and requirements/dependencies.

**Comment by christianp** [comment]
I approve of this.

**Comment by mikecroucher** [comment]
Sure. Can you demonstrate by modifying one of the contributed notebooks?

**Comment by rgaiacs** [comment]
Sure.

**Comment by rgaiacs** [comment]
Cover by #30.

**Comment by mikecroucher** [comment]
The current website implementation includes the `*` in the list of keywords. Hence, we have keywords like `* curve` instead of `curve`

**Comment by rgaiacs** [comment]
> The current website implementation includes the * in the list of keywords. Hence, we have keywords like * curve instead of curve

Proof that my regex skills aren't very good. :-( Or https://xkcd.com/1171/ is true.

**Comment by rgaiacs** [comment]
Implemented.
