### ISSUE TITLE
What should be in the template?

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/jupyter-interactions#4]
The aim is to ensure that contributed notebooks are short and to the point. The current template is rather sparse. Is it enough? What else should be added?

**Comment by vidartf** [comment]
Keywords seems to be a good point.

**Comment by mikecroucher** [comment]
Keywords have been done: https://github.com/mikecroucher/jupyter-interactions/issues/9

**Comment by mikecroucher** [comment]
How best to library dependences?
I.e. this notebook needs numpy, graphviz etc.
What do you think @takluyver ?

**Comment by takluyver** [comment]
There's some work around specifying environments in notebook metadata - see jupyter/nbformat#60. Longer term, I think that will be good for this use case once it's stabilised and there's an easy way to create the environment definition.

In the shorter term, I'd guess that something like we did for keywords is easiest. Maybe a heading *Requirements* and then something like pip requirements.txt syntax?

**Comment by christianp** [comment]
Some more information about the author would be good (all optional?):

* URL
* email address
* github username

**Comment by mikecroucher** [comment]
Would doing that affect the website code?

**Comment by christianp** [comment]
@mikecroucher Doing what?

**Comment by mikecroucher** [comment]
adding the additional author info you suggested

**Comment by mikecroucher** [comment]
I think the template is good enough for now.
