### ISSUE TITLE
Gallery view inc. thumbnails

### ISSUE THREAD

**Issue by willfurnass** [mikecroucher/jupyter-interactions#8]
Would be good to have an attractive gallery view.  Could either use curated thumbnails or decide on an automated way of generating thumbnails.   Could also turn off fine detail (axes labels etc) for thumbnails.

**Comment by vidartf** [comment]
A possible way would be to have a specific spot in the template for where to extract thumbnails, see #4.

**Comment by willfurnass** [comment]
We use `nbconvert` and a custom Exporter to generate clean thumbnails?

**Comment by mikecroucher** [comment]
Thanks to @christianp we now have a demo for this.
