### ISSUE TITLE
Keywords and subject classification

### ISSUE THREAD

**Issue by willfurnass** [mikecroucher/jupyter-interactions#9]
Tag by both discipline and widget type?  

How to embed tags in Notebooks?  Separate cell(s) at the bottom of each Notebook?  

For discipline we could use the [2010 Mathematics Subject Classification](http://www.ams.org/msc/msc2010.html)

**Comment by mikecroucher** [comment]
It was agreed that all we need is a Markdown cell with the header 'keywords' and a comma separated list. I added this to the template in https://github.com/mikecroucher/jupyter-interactions/commit/b3e7d9a3ec29d1e64198d17a90cf9005b342783f
